apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "library-chart.fullname" . }}-opencode
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
data:
  opencode.jsonc: |
{{ .Values.opencode.config | indent 4 }}
