apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "library-chart.fullname" . }}-app
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
data:
  app.py: |
{{ .Files.Get "files/app.py" | indent 4 }}
