global:
  suspend: false
tjeneste:
  version: jd3.2.4-2025.09.29T01_51Z
  pullPolicy: Always
security:
  networkPolicy:
    enabled: false
    from: []
  allowlist:
    enabled: false
    ip: 0.0.0.0/0
  serviceEntry:
    enabled: true
    hosts:
      - storage.googleapis.com
  oauth2:
    provider: keycloak-oidc
    oidcIssuerUrl: overwritten-by-onyxia
    clientId: my-client
    authenticatedEmails: ''
environment:
  user: onyxia
  group: users
features:
  toggle_new_variables_workspace: false
userAttributes:
  environmentVariableName: OIDC_TOKEN
  userAttribute: access_token
  value: ''
dapla:
  sourceData:
    reason: ''
    requestedDuration: 4h
  group: dapla-felles-developers
  sharedBuckets: []
oidc:
  enabled: true
  tokenExchangeUrl: ''
  configMapName: ''
replicaCount: 1
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
kubernetes:
  enabled: false
  role: view
podAnnotations: {}
podLabels:
  onyxia.app: jdemetra
podSecurityContext:
  fsGroup: 100
securityContext: {}
networking:
  type: ClusterIP
  clusterIP: None
  service:
    port: 6080
  user:
    enabled: false
istio:
  enabled: false
  gateways:
    - istio-namespace/example-gateway
  hostname: chart-example.local
  userHostname: chart-example-user.local
ressurser:
  requests:
    cpu: ''
    memory: ''
diskplass:
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi
avansert:
  data:
    mountStandard: true
  startupScript:
    scriptPath: ''
    scriptArgs: ''
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
startupProbe:
  failureThreshold: 60
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 30
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi
init:
  standardInitPath: /opt/onyxia-init.sh
  regionInit: ''
