apiVersion: v2
name: jupyter-playground
description: Jupyterlab med Python og R og mange vanlige pakker ferdig installert. Passer godt for de som skal lære R og Python uten for mye kompleksitet.
icon: https://raw.githubusercontent.com/statisticsnorway/dapla-lab-helm-charts-services/d881cef65161a7209ac7c85fbcb6608581249dc1/icons/jupyter.png
keywords:
  - Jupyter
  - Python
home: https://manual.dapla.ssb.no/statistikkere/jupyter-playground.html
sources:
  - https://github.com/statisticsnorway/dapla-lab-helm-charts-standard-test
  - https://github.com/statisticsnorway/dapla-lab-images
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.5.21


dependencies:
  - name: library-chart
    version: 4.2.0
    repository: https://statisticsnorway.github.io/dapla-lab-helm-charts-library
