on:
  pull_request:
    paths:
      - 'charts/jdemetra/values.schema.json'
      - 'charts/jupyter/values.schema.json'
      - 'charts/jupyter-playground/values.schema.json'
      - 'charts/jupyter-pyspark/values.schema.json'
      - 'charts/rstudio/values.schema.json'
      - 'charts/vscode-python/values.schema.json'

jobs:
  detect:
    name: Detect changed 'values.schema.json' files
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.changed.outputs.files_json }}

    steps:
      - uses: actions/checkout@v5

      - name: Get changed 'values.schema.json files
        id: changed
        run: |
          # Compare commits properly for both push and PR events
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git fetch origin ${{ github.base_ref }} --depth=1
            files=$(git diff --name-only origin/${{ github.base_ref }} HEAD | grep 'values.schema.json' || true)
          else
            files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'values.schema.json' || true)
          fi

          echo "Changed files:"
          echo "$files"

          # Convert to JSON array for the matrix
          files_json=$(printf '%s\n' "$files" | jq -R -s -c 'split("\n")[:-1]')
          echo "files_json=$files_json" >> $GITHUB_OUTPUT

  process:
    name: Process each changed file
    needs: detect
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJson(needs.detect.outputs.files) }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: astral-sh/setup-uv@v7.1.0
        with:
          version: 'latest'
          python-version: '3.13'

      - name: Run schema test script for ${{ matrix.file }}
        run: |
          uv run test/schema.py "${{ matrix.file }}"
